SELECT 
COUNT(1) as TOTAL_CONVERSIONS,
ROUND(AVG(ACTIVATION_DAYS), 1) as AVG_CONVERSION_DAYS,
ROUND(AVG(ACTIVATION_HOURS), 1) as AVG_CONVERSION_HOURS,
ROUND(AVG(ACTIVATION_MINUTES), 1) as AVG_CONVERSION_MINUTES 
FROM {{ ref('deputy_paid_conversions_silver') }}